name: CI

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  JAVA_OPTS: >-
    -Xms4096M -Xmx4096M -Xss6M
    -Dfile.encoding=UTF-8
    --add-opens java.base/java.lang=ALL-UNNAMED

jobs:
  test_scala_213:
    name: Test (Scala 2.13)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      name: Cache Embedded Cassandra
      with:
        path: |
          ~/.embedded-cassandra
        key: cassandra-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**') }}
    - uses: coursier/cache-action@v6
      with:
        extraKey: '2.13'
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: sbt -v 'scala213 test'

  test_scala_212:
    name: Test (Scala 2.12)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
      with:
        extraKey: '2.12'
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: sbt -v 'scala212 test' quine/assembly quine-docs/makeSite 'scalafixAll --check'

  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
      with:
        extraKey: 'fmt'
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: sbt -v scalafmtCheckAll scalafmtSbtCheck

